openapi: 3.0.0
info:
  title: Demo API
  description: REST API demonstrating how to integrate into a CloudFront distribution.
  version: 0.1.0

servers:
  - url: /api

x-amazon-apigateway-gateway-responses:
  DEFAULT_4XX:
    ResponseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
      gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      gatewayresponse.header.Access-Control-Allow-Methods: '''*'''
  UNAUTHORIZED:
    ResponseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
      gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      gatewayresponse.header.Access-Control-Allow-Methods: '''*'''
      StatusCode: '401'
  EXPIRED_TOKEN:
    ResponseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
      gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      gatewayresponse.header.Access-Control-Allow-Methods: '''*'''
      StatusCode: '401'

components:
  schemas:
    HelloWorldResponse:
      properties:
        message:
          type: string

paths:
  /hello:
    get:
      summary: Hello world endpoint.
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorldResponse'

      x-amazon-apigateway-integration:
        uri: "{{helloworld-lambda}}"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
